spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
        registration:
          kakao:
            client-id: ENC("dj/BMDa5fSYOopikkMAqNRjWEl/j5XAHs4JvRs6qjWwxtU4yNyLObSvmp2ZbQYrY")
            client-secret: ENC("nHO/EGPshiYS7a6Y/UcmDQl1gL5Ttvo9uL28QUn7felFFt7XdvJdGFupJ3Iq0DeF")
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email # 비즈 혹은 테스트 앱일 경우에만 제공됨
          google:
            client-id: ENC("MMf3qBNYW9q7Is8tGzHmyohLN1CLVTQ658fSJEmGShSinszKZfEg469CpTVBn/n6x//HJ3llb6fuex6hCy0TSNDR3cN86AN7SpyMZvxMGA/jHO2fZPbzFg==")
            client-secret: ENC("ceFxX0Eih0uXJc73t3zHiTl6hLKEy7b1ou4LrycVUhNMdLR0Hceu2+UkSU56TG3b")
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope: email, openid
